config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/me/:id', to: 'home#show', as: 'me'

  resources :admin_users, only: [:index, :edit, :update]

  get 'missing/courses', to:'user_courses#missing'
  get 'done/courses', to:'user_courses#done'
  patch 'done/courses/patch', to:'user_courses#toggle'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :chart do
    get '/topics/:id/:topic', to: 'users#topics', as: 'users_topics'
    get '/topics/:topic', to: 'admins#topics', as: 'admins_topics'
      namespace :users do
      end
      namespace :admins do
      end
  end
end

app/controllers/user_courses_controller.rb
class UserCoursesController < ApplicationController
  def index
    if params[:topic]
      @topic = Topic.find_by(id: params[:topic])
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: params[:topic], user_id: current_user.id), items: 10)
    else
      @topic = Topic.first
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: 1, user_id: current_user.id), items: 10)
    end
  end

  def edit
    @user_course = UserCourse.find_by(course_id: params[:id], user_id: current_user.id)
  end

  def update
    @user_course = UserCourse.find_by(course_id: params[:id], user_id: current_user.id)
    if @user_course.update(user_courses_params)
      flash[:notice] = "Course was updated successfully."
      redirect_to user_courses_path
    else
      render 'edit'
    end
  end

  def new
    @user_course = UserCourse.new
  end
  
  def create
    @user_course = Category.new(user_courses_params)
    if @user_course.save
      flash[:notice] = "Category was successfully created"
      redirect_to @user_course
    else
      render 'new'
    end
  end
  
  def missing
    if params[:topic]
      @topic = Topic.find_by(id: params[:topic])
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: params[:topic], finished: false), items: 10)
    else
      @topic = Topic.first
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: 1, finished: false), items: 10)
    end
  end

  def done
    if params[:topic]
      @topic = Topic.find_by(id: params[:topic])
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: params[:topic], finished: true), items: 10)
    else
      @topic = Topic.first
      @pagy, @user_courses = pagy(UserCourse.where(topic_id: 1, finished: true), items: 10)
    end
  end

  def toggle
    @user_course = UserCourse.find_by(course_id: params[:course_id], user_id: current_user.id)
    if @user_course.update(finished: params[:finished])
      flash[:notice] = "Course was updated successfully."
      redirect_to request.referrer
    else
      redirect_to request.referrer
    end
  end
  private

  def user_courses_params
    params.require(:user_course).permit(:finished)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/views/user_courses/_form.html.erb
<%= form_with(model: @user_course, local: true) do |f|%>
  <div class="form-group">
    <%= f.label :topic_id, class: "form-label" %>
    <%= f.text_field :topic_id, class:  "form-control", placeholder: "Enter title", :disabled => true %>
  </div>
  <div class="form-group">
    <%= f.label :course_id, class: "form-label" %>
    <%= f.text_field :course_id, class:  "form-control", placeholder: "Enter title", :disabled => true %>
  </div>
  <div class="form-group">
    <%= f.label :finished, class: "form-label" %>
    <%= f.check_box :finished, class:  "form-control", placeholder: "Enter title"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-outline-primary btn-lg"%>
  </div>
<% end %>

app/views/user_courses/done.html.erb
<div class="container-fluid">
  <h1 class="mt-4">Courses Done</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active"><%= @topic.name %></li>
  </ol>

  

<ul class="nav nav-tabs">
  <% Topic.all.each do |t|%>
    <li class="nav-item">
        <!--a href="#home" class="nav-link <%= " active" if @count==0 %>" data-toggle="tab"><%= t.name %></a-->
        <%  if t == @topic %>
          <%= link_to t.name, done_courses_path(:topic => t.id), :class => 'nav-link active' %>
        <% else %>
          <%= link_to t.name, done_courses_path(:topic => t.id), :class => 'nav-link' %>
        <% end %>
    </li>
    <% @count = 1 %>
  <% end %>
</ul>


  <table class="table table-hover">
  <thead>
    <tr>
      <!--th scope="col">Topic</th-->
      <th scope="col">Name</th>
      <th scope="col">Due Date</th>
      <th scope="col">Finished?</th>
      <th scope="col">Days</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user_courses.each do |course| %>
      <% if course.user_id == current_user.id || current_user.role == Role.last %>
        <tr class="<%= 'table-success' if course.finished%>">
          <!--th scope="row"><%= course.course.topic.name %></th-->
          <td><%= truncate(course.course.name, length: 30) %></td>
          <% if course.course.due_date.to_date.past? %>
            <td><%= time_ago_in_words(course.course.due_date)%> ago</td>
          <% else %>
            <td><%= time_ago_in_words(course.course.due_date)%> from today</td>
          <% end %>
          <td><%== human_boolean(course.finished) %></td>
          <td><%= time_ago_in_words(course.date_finished) if course.date_finished %></td>
          <!--td>
            <%= link_to "incomplete", edit_user_course_path(course), class: "btn btn-outline-info btn-sm" %>
          </td-->
          <td>
          <%= form_tag done_courses_patch_path(course), method: :patch do -%>
            <%= hidden_field_tag :finished, false -%>
            <%= hidden_field_tag :course_id, course.course.id -%>
            <%= submit_tag 'incomplete', class: "btn btn-outline-danger btn-sm", data: {confirm: "Are you sure?"} -%>
          <%- end -%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<%== pagy_bootstrap_nav(@pagy) %>

app/views/user_courses/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Finish course?
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to course listing ]', user_courses_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_courses/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4">All Courses</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active"><%= @topic.name %></li>
  </ol>

  

<ul class="nav nav-tabs">
  <% Topic.all.each do |t|%>
    <li class="nav-item">
        <!--a href="#home" class="nav-link <%= " active" if @count==0 %>" data-toggle="tab"><%= t.name %></a-->
        <%  if t == @topic %>
          <%= link_to t.name, user_courses_path(:topic => t.id), :class => 'nav-link active' %>
        <% else %>
          <%= link_to t.name, user_courses_path(:topic => t.id), :class => 'nav-link' %>
        <% end %>
    </li>
    <% @count = 1 %>
  <% end %>
</ul>


  <table class="table table-hover">
  <thead>
    <tr>
      <!--th scope="col">Topic</th-->
      <th scope="col">Name</th>
      <th scope="col">Due Date</th>
      <th scope="col" class="text-center">Finished?</th>
      <th scope="col">Days</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user_courses.each do |course| %>
      <% if course.user_id == current_user.id || current_user.role == Role.last %>
        <tr class="<%= 'table-success' if course.finished%>">
          <!--th scope="row"><%= course.course.topic.name %></th-->
          <td><%= truncate(course.course.name, length: 30) %></td>
          <% if course.course.due_date.to_date.past? %>
            <td><%= time_ago_in_words(course.course.due_date)%> ago</td>
          <% else %>
            <td><%= time_ago_in_words(course.course.due_date)%> from today</td>
          <% end %>
          <td class="text-center"><%== human_boolean(course.finished) %></td>
          <td><%= time_ago_in_words(course.date_finished) if course.date_finished %></td>
          <td class="text-center">
          <% if course.finished %>
            <%= form_tag done_courses_patch_path(course), method: :patch do -%>
              <%= hidden_field_tag :finished, false -%>
              <%= hidden_field_tag :course_id, course.course.id -%>
              <%= submit_tag 'incomplete', class: "btn btn-outline-danger btn-sm", data: {confirm: "Are you sure?"} -%>
            <%- end -%>
          <% else %>
            <%= form_tag done_courses_patch_path(course), method: :patch do -%>
              <%= hidden_field_tag :finished, true -%>
              <%= hidden_field_tag :course_id, course.course.id -%>
              <%= submit_tag 'Done', class: "btn btn-outline-info btn-sm" -%>
            <%- end -%>
          <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<%== pagy_bootstrap_nav(@pagy) %>

</div>

app/views/user_courses/missing.html.erb
<div class="container-fluid">
  <h1 class="mt-4">Courses Missing</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active"><%= @topic.name %></li>
  </ol>

  

<ul class="nav nav-tabs">
  <% Topic.all.each do |t|%>
    <li class="nav-item">
        <!--a href="#home" class="nav-link <%= " active" if @count==0 %>" data-toggle="tab"><%= t.name %></a-->
        <%  if t == @topic %>
          <%= link_to t.name, missing_courses_path(:topic => t.id), :class => 'nav-link active' %>
        <% else %>
          <%= link_to t.name, missing_courses_path(:topic => t.id), :class => 'nav-link' %>
        <% end %>
    </li>
    <% @count = 1 %>
  <% end %>
</ul>


  <table class="table table-hover">
  <thead>
    <tr>
      <!--th scope="col">Topic</th-->
      <th scope="col">Name</th>
      <th scope="col">Due Date</th>
      <th scope="col">Finished?</th>
      <th scope="col">Days</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @user_courses.each do |course| %>
      <% if course.user_id == current_user.id || current_user.role == Role.last %>
        <tr class="<%= 'table-success' if course.finished%>">
          <!--th scope="row"><%= course.course.topic.name %></th-->
          <td><%= truncate(course.course.name, length: 30) %></td>
          <% if course.course.due_date.to_date.past? %>
            <td><%= time_ago_in_words(course.course.due_date)%> ago</td>
          <% else %>
            <td><%= time_ago_in_words(course.course.due_date)%> from today</td>
          <% end %>
          <td><%== human_boolean(course.finished) %></td>
          <td><%= time_ago_in_words(course.date_finished) if course.date_finished %></td>
          <td>
            <%= form_tag done_courses_patch_path(course), method: :patch do -%>
              <%= hidden_field_tag :finished, true -%>
              <%= hidden_field_tag :course_id, course.course.id -%>
              <%= submit_tag 'Done', class: "btn btn-outline-info btn-sm" -%>
            <%- end -%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<%== pagy_bootstrap_nav(@pagy) %>

app/views/user_courses/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Register new course
        </div>
        <div class="card-body">  

          <%= render 'form' %>
          
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to categories listing ]', user_courses_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>