config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/me/:id', to: 'home#show', as: 'me'

  resources :admin_users, only: [:index, :edit, :update]

  get 'missing/courses', to:'user_courses#missing'
  get 'done/courses', to:'user_courses#done'
  patch 'done/courses/patch', to:'user_courses#toggle'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :chart do
    get '/topics/:id/:topic', to: 'users#topics', as: 'users_topics'
    get '/topics/:topic', to: 'admins#topics', as: 'admins_topics'
      namespace :users do
      end
      namespace :admins do
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
    # @key_map = {1 => "Technical", 2 => "Practical", 3 => "Soft Skill", 4 => "Atos Training", 5 => "project", 6 => "Other"}
    if current_user.role.id == 1
      redirect_to me_path(current_user)
    elsif current_user.role.id == 2
      @users = User.all
    else
      @users = User.all
      @key_map = {1 => "Technical", 2 => "Practical", 3 => "Soft Skill", 4 => "Atos Training", 5 => "project", 6 => "Other"}
      @percent = (UserCourse.where(finished: true ).count.to_f / Course.all.count * 100).round(2)
    end
    # User.find_by(email: current_user.email).courses.select { |x| x.topic_id == 6 }
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user || current_user.role.id > 1
      @key_map = {1 => "Technical", 2 => "Practical", 3 => "Soft Skill", 4 => "Atos Training", 5 => "project", 6 => "Other"}
      @percent = (UserCourse.where(user_id: current_user.id, finished: true ).count.to_f / Course.all.count * 100).round(2)
    else
      flash[:alert] = "Unauthorized."
      redirect_to me_path(current_user)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4">Dashboard</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active">Overall Performance</li>
  </ol>
  <div class="container">
    <div class="row-fluid">
      <div class="card">
        <div class="card-body">
          <div class="row-fluid">
            <div class="progress" style="height: 35px;">
              <div class="progress-bar" role="progressbar" style="width: <%= @percent %>%;" aria-valuenow="<%= @percent %>" aria-valuemin="0" aria-valuemax="100"><%= @percent %>%</div>
            </div>
          </div>
          <div class="container">
            <div class="row mt-3">
              <h5>Course: <strong>Ignite</strong></h5>
            </div> 
            <div class="row mt-2">
             <i class="far fa-clock mr-1 "></i><h6>Length: 12 weeks</h6>
            </div> 
          <div>      
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-2 mx-auto">
    <% Topic.all.each do |t|%>
      <div class="col-4 text-center">
        <span><%= t.name %></span>
        <%= pie_chart chart_admins_topics_path(t), download: true, donut: true, width: "200px", height: "150px", suffix: "%" %>
      </div>
    <% end %>
  </div>
  <br><br><br>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active">Individual Performance</li>
  </ol>
  <div class="row">
  
    <% @users.each do |u| %>
        <div class="col-xl-4 col-md-6">
          <div class="card bg-primary text-white mb-4">
            <div class="card-body"><%= u.name %></div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <%= link_to 'View details', me_path(u), class: "small text-white stretched-link" %>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
          </div>
        </div>
    <% end %>
    
  </div>
</div>

app/views/home/show.html.erb
<div class="container-fluid">
  <h1 class="mt-4"><%= @user.name %></h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active">Overall Performance</li>
  </ol>
<%= link_to "Back", :back %>
  <div class="row justify-content-center mt-2 mx-auto">
      <% Topic.all.each do |t|%>
      <div class="col-4 text-center">
        <span><%= t.name %></span>
        <%= pie_chart chart_users_topics_path(@user, t), download: true, donut: true, width: "200px", height: "150px", suffix: "%" %>
      </div>
    <% end %>
  </div>


  <br><br><br>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active">Individual Performance</li>
  </ol>
  <div class="row">
  <span>work in progress</span>
  </div>
</div>