config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/me/:id', to: 'home#show', as: 'me'

  resources :admin_users, only: [:index, :edit, :update]

  get 'missing/courses', to:'user_courses#missing'
  get 'done/courses', to:'user_courses#done'
  patch 'done/courses/patch', to:'user_courses#toggle'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :chart do
    get '/topics/:id/:topic', to: 'users#topics', as: 'users_topics'
    get '/topics/:topic', to: 'admins#topics', as: 'admins_topics'
      namespace :users do
      end
      namespace :admins do
      end
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController 
  before_action :set_user, only: [:edit, :update]

  def index
    if params[:role_id]
      @role = Role.find_by(id: params[:role_id])
      @pagy, @users = pagy(User.where(role_id: params[:role_id]), items: 10)
    else
      @role = Role.find_by(id: 1)
      @pagy, @users = pagy(User.where(role_id: 1), items: 10)
    end
  end

  def edit
    
  end
  
  def update
    
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully."
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  private
   
   # Use callbacks to share common setup or constraints between actions.
   def set_user
      @user = User.find(params[:id])
   end
   
   # Never trust parameters from the scary internet, only allow the white list through.
   def user_params
      params.require(:user).permit(:role_id)
   end
end

app/views/admin_users/edit.html.erb
<div class="container-fluid">
  <h1 class="mt-4">All Users</h1>
  
  
  <div class="card shadow-lg border-0 rounded-lg">
    <div class="card-header">
      <h3 class="text-center font-weight-light my-4"><%= @user.name %></h3>
    </div>
    <div class="card-body">
      <%= form_for(@user, :url =>{:action => 'update'}) do |f| %>
        <div class="form-group">
          <%= f.label :role_id, class: "form-label" %>
          <%= f.select :role_id, options_for_select(Role.all.collect { | role | [role.name, role.id] }), {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-outline-primary btn-lg"%>
        </div>
      <% end %>
      <div class="card-footer text-center">
        <%= link_to "Back", :back %>
      </div>
    </div>  
  </div> 

</div>

app/views/admin_users/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4">All Users</h1>
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active"><%= @role.name %></li>
  </ol>

  

<ul class="nav nav-tabs">
  <% Role.all.each do |r|%>
    <li class="nav-item">
        <%  if r == @role %>
          <%= link_to r.name, admin_users_path(:role_id => r.id), :class => 'nav-link active' %>
        <% else %>
          <%= link_to r.name, admin_users_path(:role_id => r.id), :class => 'nav-link' %>
        <% end %>
    </li>
    <% @count = 1 %>
  <% end %>
</ul>


  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      
        <tr>
          <td><%= truncate(u.name, length: 30) %></td>
          <td><%= u.email %></td>
          <td><%= u.role.name%></td>
          <td><%= link_to 'edit', edit_admin_user_path(u) %></td>
        </tr>
      
    <% end %>
  </tbody>
</table>


<%== pagy_bootstrap_nav(@pagy) %>

</div>