config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
  get '/me/:id', to: 'home#show', as: 'me'

  resources :admin_users, only: [:index, :edit, :update]

  get 'missing/courses', to:'user_courses#missing'
  get 'done/courses', to:'user_courses#done'
  patch 'done/courses/patch', to:'user_courses#toggle'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :chart do
    get '/topics/:id/:topic', to: 'users#topics', as: 'users_topics'
    get '/topics/:topic', to: 'admins#topics', as: 'admins_topics'
      namespace :users do
      end
      namespace :admins do
      end
  end
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-light mt-auto navbar-fixed-bottom">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Hayashi 2020</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">Core</div>
            <a class="nav-link" href="<%= root_path %>">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>
            <% if current_user.role.id == 2 || current_user.role.id == 3 %>
            <div class="sb-sidenav-menu-heading">Users</div>
            <a class="nav-link" href="<%= admin_users_path %>">
                <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                Gestionar
            </a>
            <% end %>
            <div class="sb-sidenav-menu-heading">Courses</div>
            <a class="nav-link" href=<%= user_courses_path %>>
                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                See all
            </a>
            <% if current_user.role.id == 1 %>
                <a class="nav-link" href=<%= missing_courses_path %>>
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Missing
                </a>
                <a class="nav-link" href=<%= done_courses_path %>>
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Done
                </a>
            <% end %>
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        <%= current_user.name %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IgniteTracker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>
  <body class="sb-nav-fixed">
    <%= render 'layouts/navbar' %>
    <% if user_signed_in? %>
      <div id="layoutSidenav">
      <!--    side Navbar  -->
          <%= render 'layouts/sidebar' %>
        <!--    content  -->
        <div id="layoutSidenav_content">
          <main>
            <div class="container-fluid">
              <%= render 'layouts/messages'%>
              <%= yield %>
            </div>
          </main>
        </div>
      <!--    end content  -->
      </div>
    <% else %>
      <main>
          <%= yield %>
      </main>
    <% end %>
    
    
    <!--    end content  -->
    <%= render 'layouts/footer' %>
    
    <%= javascript_pack_tag 'global' %>
  </body>
</html>